//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace HCM401kData.DataClient {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserTickerItem", Namespace="http://tempuri.org/")]
    public partial class UserTickerItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string UserNameField;
        
        private string LastNameField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string DefaultTikerField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DefaultTiker {
            get {
                return this.DefaultTikerField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultTikerField, value) != true)) {
                    this.DefaultTikerField = value;
                    this.RaisePropertyChanged("DefaultTiker");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.ObjectModel.ObservableCollection<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryRequest", Namespace="http://tempuri.org/")]
    public partial class HistoryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string SymbolField;
        
        private HCM401kData.DataClient.Periodicity periodicityField;
        
        private int periodField;
        
        private string IDField;
        
        private int MaxAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public HCM401kData.DataClient.Periodicity periodicity {
            get {
                return this.periodicityField;
            }
            set {
                if ((this.periodicityField.Equals(value) != true)) {
                    this.periodicityField = value;
                    this.RaisePropertyChanged("periodicity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int period {
            get {
                return this.periodField;
            }
            set {
                if ((this.periodField.Equals(value) != true)) {
                    this.periodField = value;
                    this.RaisePropertyChanged("period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int MaxAmount {
            get {
                return this.MaxAmountField;
            }
            set {
                if ((this.MaxAmountField.Equals(value) != true)) {
                    this.MaxAmountField = value;
                    this.RaisePropertyChanged("MaxAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Periodicity", Namespace="http://tempuri.org/")]
    public enum Periodicity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Day = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Week = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Month = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BarInfo", Namespace="http://tempuri.org/")]
    public partial class BarInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<HCM401kData.DataClient.Bar> BarsField;
        
        private HCM401kData.DataClient.HistoryRequest TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<HCM401kData.DataClient.Bar> Bars {
            get {
                return this.BarsField;
            }
            set {
                if ((object.ReferenceEquals(this.BarsField, value) != true)) {
                    this.BarsField = value;
                    this.RaisePropertyChanged("Bars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public HCM401kData.DataClient.HistoryRequest Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bar", Namespace="http://tempuri.org/")]
    public partial class Bar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double OpenField;
        
        private double HighField;
        
        private double LowField;
        
        private double CloseField;
        
        private double VolumeField;
        
        private System.DateTime TimeStampField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Open {
            get {
                return this.OpenField;
            }
            set {
                if ((this.OpenField.Equals(value) != true)) {
                    this.OpenField = value;
                    this.RaisePropertyChanged("Open");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double High {
            get {
                return this.HighField;
            }
            set {
                if ((this.HighField.Equals(value) != true)) {
                    this.HighField = value;
                    this.RaisePropertyChanged("High");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Low {
            get {
                return this.LowField;
            }
            set {
                if ((this.LowField.Equals(value) != true)) {
                    this.LowField = value;
                    this.RaisePropertyChanged("Low");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Close {
            get {
                return this.CloseField;
            }
            set {
                if ((this.CloseField.Equals(value) != true)) {
                    this.CloseField = value;
                    this.RaisePropertyChanged("Close");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataClient.HCM401kConnectorSoap")]
    public interface HCM401kConnectorSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetUserTickerData", ReplyAction="*")]
        System.IAsyncResult BeginGetUserTickerData(HCM401kData.DataClient.GetUserTickerDataRequest request, System.AsyncCallback callback, object asyncState);
        
        HCM401kData.DataClient.GetUserTickerDataResponse EndGetUserTickerData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetDefaultTicker", ReplyAction="*")]
        System.IAsyncResult BeginGetDefaultTicker(HCM401kData.DataClient.GetDefaultTickerRequest request, System.AsyncCallback callback, object asyncState);
        
        HCM401kData.DataClient.GetDefaultTickerResponse EndGetDefaultTicker(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetAvailableTickers", ReplyAction="*")]
        System.IAsyncResult BeginGetAvailableTickers(HCM401kData.DataClient.GetAvailableTickersRequest request, System.AsyncCallback callback, object asyncState);
        
        HCM401kData.DataClient.GetAvailableTickersResponse EndGetAvailableTickers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetHistoricalDataX", ReplyAction="*")]
        System.IAsyncResult BeginGetHistoricalDataX(HCM401kData.DataClient.GetHistoricalDataXRequest request, System.AsyncCallback callback, object asyncState);
        
        HCM401kData.DataClient.GetHistoricalDataXResponse EndGetHistoricalDataX(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserTickerDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserTickerData", Namespace="http://tempuri.org/", Order=0)]
        public HCM401kData.DataClient.GetUserTickerDataRequestBody Body;
        
        public GetUserTickerDataRequest() {
        }
        
        public GetUserTickerDataRequest(HCM401kData.DataClient.GetUserTickerDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserTickerDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetUserTickerDataRequestBody() {
        }
        
        public GetUserTickerDataRequestBody(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserTickerDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserTickerDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public HCM401kData.DataClient.GetUserTickerDataResponseBody Body;
        
        public GetUserTickerDataResponse() {
        }
        
        public GetUserTickerDataResponse(HCM401kData.DataClient.GetUserTickerDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserTickerDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<HCM401kData.DataClient.UserTickerItem> GetUserTickerDataResult;
        
        public GetUserTickerDataResponseBody() {
        }
        
        public GetUserTickerDataResponseBody(System.Collections.ObjectModel.ObservableCollection<HCM401kData.DataClient.UserTickerItem> GetUserTickerDataResult) {
            this.GetUserTickerDataResult = GetUserTickerDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDefaultTickerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDefaultTicker", Namespace="http://tempuri.org/", Order=0)]
        public HCM401kData.DataClient.GetDefaultTickerRequestBody Body;
        
        public GetDefaultTickerRequest() {
        }
        
        public GetDefaultTickerRequest(HCM401kData.DataClient.GetDefaultTickerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDefaultTickerRequestBody {
        
        public GetDefaultTickerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDefaultTickerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDefaultTickerResponse", Namespace="http://tempuri.org/", Order=0)]
        public HCM401kData.DataClient.GetDefaultTickerResponseBody Body;
        
        public GetDefaultTickerResponse() {
        }
        
        public GetDefaultTickerResponse(HCM401kData.DataClient.GetDefaultTickerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDefaultTickerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDefaultTickerResult;
        
        public GetDefaultTickerResponseBody() {
        }
        
        public GetDefaultTickerResponseBody(string GetDefaultTickerResult) {
            this.GetDefaultTickerResult = GetDefaultTickerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableTickersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableTickers", Namespace="http://tempuri.org/", Order=0)]
        public HCM401kData.DataClient.GetAvailableTickersRequestBody Body;
        
        public GetAvailableTickersRequest() {
        }
        
        public GetAvailableTickersRequest(HCM401kData.DataClient.GetAvailableTickersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAvailableTickersRequestBody {
        
        public GetAvailableTickersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableTickersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableTickersResponse", Namespace="http://tempuri.org/", Order=0)]
        public HCM401kData.DataClient.GetAvailableTickersResponseBody Body;
        
        public GetAvailableTickersResponse() {
        }
        
        public GetAvailableTickersResponse(HCM401kData.DataClient.GetAvailableTickersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAvailableTickersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HCM401kData.DataClient.ArrayOfString GetAvailableTickersResult;
        
        public GetAvailableTickersResponseBody() {
        }
        
        public GetAvailableTickersResponseBody(HCM401kData.DataClient.ArrayOfString GetAvailableTickersResult) {
            this.GetAvailableTickersResult = GetAvailableTickersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHistoricalDataXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHistoricalDataX", Namespace="http://tempuri.org/", Order=0)]
        public HCM401kData.DataClient.GetHistoricalDataXRequestBody Body;
        
        public GetHistoricalDataXRequest() {
        }
        
        public GetHistoricalDataXRequest(HCM401kData.DataClient.GetHistoricalDataXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHistoricalDataXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HCM401kData.DataClient.HistoryRequest token;
        
        public GetHistoricalDataXRequestBody() {
        }
        
        public GetHistoricalDataXRequestBody(HCM401kData.DataClient.HistoryRequest token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHistoricalDataXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHistoricalDataXResponse", Namespace="http://tempuri.org/", Order=0)]
        public HCM401kData.DataClient.GetHistoricalDataXResponseBody Body;
        
        public GetHistoricalDataXResponse() {
        }
        
        public GetHistoricalDataXResponse(HCM401kData.DataClient.GetHistoricalDataXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHistoricalDataXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HCM401kData.DataClient.BarInfo GetHistoricalDataXResult;
        
        public GetHistoricalDataXResponseBody() {
        }
        
        public GetHistoricalDataXResponseBody(HCM401kData.DataClient.BarInfo GetHistoricalDataXResult) {
            this.GetHistoricalDataXResult = GetHistoricalDataXResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HCM401kConnectorSoapChannel : HCM401kData.DataClient.HCM401kConnectorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserTickerDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserTickerDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<HCM401kData.DataClient.UserTickerItem> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<HCM401kData.DataClient.UserTickerItem>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDefaultTickerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDefaultTickerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAvailableTickersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAvailableTickersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HCM401kData.DataClient.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HCM401kData.DataClient.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetHistoricalDataXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetHistoricalDataXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HCM401kData.DataClient.BarInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HCM401kData.DataClient.BarInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HCM401kConnectorSoapClient : System.ServiceModel.ClientBase<HCM401kData.DataClient.HCM401kConnectorSoap>, HCM401kData.DataClient.HCM401kConnectorSoap {
        
        private BeginOperationDelegate onBeginGetUserTickerDataDelegate;
        
        private EndOperationDelegate onEndGetUserTickerDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserTickerDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDefaultTickerDelegate;
        
        private EndOperationDelegate onEndGetDefaultTickerDelegate;
        
        private System.Threading.SendOrPostCallback onGetDefaultTickerCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAvailableTickersDelegate;
        
        private EndOperationDelegate onEndGetAvailableTickersDelegate;
        
        private System.Threading.SendOrPostCallback onGetAvailableTickersCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetHistoricalDataXDelegate;
        
        private EndOperationDelegate onEndGetHistoricalDataXDelegate;
        
        private System.Threading.SendOrPostCallback onGetHistoricalDataXCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public HCM401kConnectorSoapClient() {
        }
        
        public HCM401kConnectorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HCM401kConnectorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HCM401kConnectorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HCM401kConnectorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetUserTickerDataCompletedEventArgs> GetUserTickerDataCompleted;
        
        public event System.EventHandler<GetDefaultTickerCompletedEventArgs> GetDefaultTickerCompleted;
        
        public event System.EventHandler<GetAvailableTickersCompletedEventArgs> GetAvailableTickersCompleted;
        
        public event System.EventHandler<GetHistoricalDataXCompletedEventArgs> GetHistoricalDataXCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HCM401kData.DataClient.HCM401kConnectorSoap.BeginGetUserTickerData(HCM401kData.DataClient.GetUserTickerDataRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserTickerData(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetUserTickerData(string userName, string password, System.AsyncCallback callback, object asyncState) {
            HCM401kData.DataClient.GetUserTickerDataRequest inValue = new HCM401kData.DataClient.GetUserTickerDataRequest();
            inValue.Body = new HCM401kData.DataClient.GetUserTickerDataRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((HCM401kData.DataClient.HCM401kConnectorSoap)(this)).BeginGetUserTickerData(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HCM401kData.DataClient.GetUserTickerDataResponse HCM401kData.DataClient.HCM401kConnectorSoap.EndGetUserTickerData(System.IAsyncResult result) {
            return base.Channel.EndGetUserTickerData(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<HCM401kData.DataClient.UserTickerItem> EndGetUserTickerData(System.IAsyncResult result) {
            HCM401kData.DataClient.GetUserTickerDataResponse retVal = ((HCM401kData.DataClient.HCM401kConnectorSoap)(this)).EndGetUserTickerData(result);
            return retVal.Body.GetUserTickerDataResult;
        }
        
        private System.IAsyncResult OnBeginGetUserTickerData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userName = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginGetUserTickerData(userName, password, callback, asyncState);
        }
        
        private object[] OnEndGetUserTickerData(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<HCM401kData.DataClient.UserTickerItem> retVal = this.EndGetUserTickerData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserTickerDataCompleted(object state) {
            if ((this.GetUserTickerDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserTickerDataCompleted(this, new GetUserTickerDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserTickerDataAsync(string userName, string password) {
            this.GetUserTickerDataAsync(userName, password, null);
        }
        
        public void GetUserTickerDataAsync(string userName, string password, object userState) {
            if ((this.onBeginGetUserTickerDataDelegate == null)) {
                this.onBeginGetUserTickerDataDelegate = new BeginOperationDelegate(this.OnBeginGetUserTickerData);
            }
            if ((this.onEndGetUserTickerDataDelegate == null)) {
                this.onEndGetUserTickerDataDelegate = new EndOperationDelegate(this.OnEndGetUserTickerData);
            }
            if ((this.onGetUserTickerDataCompletedDelegate == null)) {
                this.onGetUserTickerDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserTickerDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserTickerDataDelegate, new object[] {
                        userName,
                        password}, this.onEndGetUserTickerDataDelegate, this.onGetUserTickerDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HCM401kData.DataClient.HCM401kConnectorSoap.BeginGetDefaultTicker(HCM401kData.DataClient.GetDefaultTickerRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDefaultTicker(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetDefaultTicker(System.AsyncCallback callback, object asyncState) {
            HCM401kData.DataClient.GetDefaultTickerRequest inValue = new HCM401kData.DataClient.GetDefaultTickerRequest();
            inValue.Body = new HCM401kData.DataClient.GetDefaultTickerRequestBody();
            return ((HCM401kData.DataClient.HCM401kConnectorSoap)(this)).BeginGetDefaultTicker(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HCM401kData.DataClient.GetDefaultTickerResponse HCM401kData.DataClient.HCM401kConnectorSoap.EndGetDefaultTicker(System.IAsyncResult result) {
            return base.Channel.EndGetDefaultTicker(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetDefaultTicker(System.IAsyncResult result) {
            HCM401kData.DataClient.GetDefaultTickerResponse retVal = ((HCM401kData.DataClient.HCM401kConnectorSoap)(this)).EndGetDefaultTicker(result);
            return retVal.Body.GetDefaultTickerResult;
        }
        
        private System.IAsyncResult OnBeginGetDefaultTicker(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetDefaultTicker(callback, asyncState);
        }
        
        private object[] OnEndGetDefaultTicker(System.IAsyncResult result) {
            string retVal = this.EndGetDefaultTicker(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDefaultTickerCompleted(object state) {
            if ((this.GetDefaultTickerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDefaultTickerCompleted(this, new GetDefaultTickerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDefaultTickerAsync() {
            this.GetDefaultTickerAsync(null);
        }
        
        public void GetDefaultTickerAsync(object userState) {
            if ((this.onBeginGetDefaultTickerDelegate == null)) {
                this.onBeginGetDefaultTickerDelegate = new BeginOperationDelegate(this.OnBeginGetDefaultTicker);
            }
            if ((this.onEndGetDefaultTickerDelegate == null)) {
                this.onEndGetDefaultTickerDelegate = new EndOperationDelegate(this.OnEndGetDefaultTicker);
            }
            if ((this.onGetDefaultTickerCompletedDelegate == null)) {
                this.onGetDefaultTickerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDefaultTickerCompleted);
            }
            base.InvokeAsync(this.onBeginGetDefaultTickerDelegate, null, this.onEndGetDefaultTickerDelegate, this.onGetDefaultTickerCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HCM401kData.DataClient.HCM401kConnectorSoap.BeginGetAvailableTickers(HCM401kData.DataClient.GetAvailableTickersRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAvailableTickers(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetAvailableTickers(System.AsyncCallback callback, object asyncState) {
            HCM401kData.DataClient.GetAvailableTickersRequest inValue = new HCM401kData.DataClient.GetAvailableTickersRequest();
            inValue.Body = new HCM401kData.DataClient.GetAvailableTickersRequestBody();
            return ((HCM401kData.DataClient.HCM401kConnectorSoap)(this)).BeginGetAvailableTickers(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HCM401kData.DataClient.GetAvailableTickersResponse HCM401kData.DataClient.HCM401kConnectorSoap.EndGetAvailableTickers(System.IAsyncResult result) {
            return base.Channel.EndGetAvailableTickers(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private HCM401kData.DataClient.ArrayOfString EndGetAvailableTickers(System.IAsyncResult result) {
            HCM401kData.DataClient.GetAvailableTickersResponse retVal = ((HCM401kData.DataClient.HCM401kConnectorSoap)(this)).EndGetAvailableTickers(result);
            return retVal.Body.GetAvailableTickersResult;
        }
        
        private System.IAsyncResult OnBeginGetAvailableTickers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAvailableTickers(callback, asyncState);
        }
        
        private object[] OnEndGetAvailableTickers(System.IAsyncResult result) {
            HCM401kData.DataClient.ArrayOfString retVal = this.EndGetAvailableTickers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAvailableTickersCompleted(object state) {
            if ((this.GetAvailableTickersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAvailableTickersCompleted(this, new GetAvailableTickersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAvailableTickersAsync() {
            this.GetAvailableTickersAsync(null);
        }
        
        public void GetAvailableTickersAsync(object userState) {
            if ((this.onBeginGetAvailableTickersDelegate == null)) {
                this.onBeginGetAvailableTickersDelegate = new BeginOperationDelegate(this.OnBeginGetAvailableTickers);
            }
            if ((this.onEndGetAvailableTickersDelegate == null)) {
                this.onEndGetAvailableTickersDelegate = new EndOperationDelegate(this.OnEndGetAvailableTickers);
            }
            if ((this.onGetAvailableTickersCompletedDelegate == null)) {
                this.onGetAvailableTickersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAvailableTickersCompleted);
            }
            base.InvokeAsync(this.onBeginGetAvailableTickersDelegate, null, this.onEndGetAvailableTickersDelegate, this.onGetAvailableTickersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HCM401kData.DataClient.HCM401kConnectorSoap.BeginGetHistoricalDataX(HCM401kData.DataClient.GetHistoricalDataXRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetHistoricalDataX(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetHistoricalDataX(HCM401kData.DataClient.HistoryRequest token, System.AsyncCallback callback, object asyncState) {
            HCM401kData.DataClient.GetHistoricalDataXRequest inValue = new HCM401kData.DataClient.GetHistoricalDataXRequest();
            inValue.Body = new HCM401kData.DataClient.GetHistoricalDataXRequestBody();
            inValue.Body.token = token;
            return ((HCM401kData.DataClient.HCM401kConnectorSoap)(this)).BeginGetHistoricalDataX(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HCM401kData.DataClient.GetHistoricalDataXResponse HCM401kData.DataClient.HCM401kConnectorSoap.EndGetHistoricalDataX(System.IAsyncResult result) {
            return base.Channel.EndGetHistoricalDataX(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private HCM401kData.DataClient.BarInfo EndGetHistoricalDataX(System.IAsyncResult result) {
            HCM401kData.DataClient.GetHistoricalDataXResponse retVal = ((HCM401kData.DataClient.HCM401kConnectorSoap)(this)).EndGetHistoricalDataX(result);
            return retVal.Body.GetHistoricalDataXResult;
        }
        
        private System.IAsyncResult OnBeginGetHistoricalDataX(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HCM401kData.DataClient.HistoryRequest token = ((HCM401kData.DataClient.HistoryRequest)(inValues[0]));
            return this.BeginGetHistoricalDataX(token, callback, asyncState);
        }
        
        private object[] OnEndGetHistoricalDataX(System.IAsyncResult result) {
            HCM401kData.DataClient.BarInfo retVal = this.EndGetHistoricalDataX(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetHistoricalDataXCompleted(object state) {
            if ((this.GetHistoricalDataXCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetHistoricalDataXCompleted(this, new GetHistoricalDataXCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetHistoricalDataXAsync(HCM401kData.DataClient.HistoryRequest token) {
            this.GetHistoricalDataXAsync(token, null);
        }
        
        public void GetHistoricalDataXAsync(HCM401kData.DataClient.HistoryRequest token, object userState) {
            if ((this.onBeginGetHistoricalDataXDelegate == null)) {
                this.onBeginGetHistoricalDataXDelegate = new BeginOperationDelegate(this.OnBeginGetHistoricalDataX);
            }
            if ((this.onEndGetHistoricalDataXDelegate == null)) {
                this.onEndGetHistoricalDataXDelegate = new EndOperationDelegate(this.OnEndGetHistoricalDataX);
            }
            if ((this.onGetHistoricalDataXCompletedDelegate == null)) {
                this.onGetHistoricalDataXCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHistoricalDataXCompleted);
            }
            base.InvokeAsync(this.onBeginGetHistoricalDataXDelegate, new object[] {
                        token}, this.onEndGetHistoricalDataXDelegate, this.onGetHistoricalDataXCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override HCM401kData.DataClient.HCM401kConnectorSoap CreateChannel() {
            return new HCM401kConnectorSoapClientChannel(this);
        }
        
        private class HCM401kConnectorSoapClientChannel : ChannelBase<HCM401kData.DataClient.HCM401kConnectorSoap>, HCM401kData.DataClient.HCM401kConnectorSoap {
            
            public HCM401kConnectorSoapClientChannel(System.ServiceModel.ClientBase<HCM401kData.DataClient.HCM401kConnectorSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetUserTickerData(HCM401kData.DataClient.GetUserTickerDataRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetUserTickerData", _args, callback, asyncState);
                return _result;
            }
            
            public HCM401kData.DataClient.GetUserTickerDataResponse EndGetUserTickerData(System.IAsyncResult result) {
                object[] _args = new object[0];
                HCM401kData.DataClient.GetUserTickerDataResponse _result = ((HCM401kData.DataClient.GetUserTickerDataResponse)(base.EndInvoke("GetUserTickerData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDefaultTicker(HCM401kData.DataClient.GetDefaultTickerRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetDefaultTicker", _args, callback, asyncState);
                return _result;
            }
            
            public HCM401kData.DataClient.GetDefaultTickerResponse EndGetDefaultTicker(System.IAsyncResult result) {
                object[] _args = new object[0];
                HCM401kData.DataClient.GetDefaultTickerResponse _result = ((HCM401kData.DataClient.GetDefaultTickerResponse)(base.EndInvoke("GetDefaultTicker", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAvailableTickers(HCM401kData.DataClient.GetAvailableTickersRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetAvailableTickers", _args, callback, asyncState);
                return _result;
            }
            
            public HCM401kData.DataClient.GetAvailableTickersResponse EndGetAvailableTickers(System.IAsyncResult result) {
                object[] _args = new object[0];
                HCM401kData.DataClient.GetAvailableTickersResponse _result = ((HCM401kData.DataClient.GetAvailableTickersResponse)(base.EndInvoke("GetAvailableTickers", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetHistoricalDataX(HCM401kData.DataClient.GetHistoricalDataXRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetHistoricalDataX", _args, callback, asyncState);
                return _result;
            }
            
            public HCM401kData.DataClient.GetHistoricalDataXResponse EndGetHistoricalDataX(System.IAsyncResult result) {
                object[] _args = new object[0];
                HCM401kData.DataClient.GetHistoricalDataXResponse _result = ((HCM401kData.DataClient.GetHistoricalDataXResponse)(base.EndInvoke("GetHistoricalDataX", _args, result)));
                return _result;
            }
        }
    }
}
